name: uhelp_x64_testrun

on:
  workflow_dispatch:

jobs:

  testrun:

    runs-on: ubuntu-latest

      call-workflow:
        uses: github.com/Suletta-Majo/uhelp/.github/workflows/uhelp_autodeb.yml@v1
        secrets:
          envPAT: ${{ secrets.PERSONAL_PRIV_TOKEN }}

      - name: install uhelp and check directory
        run: |
          apt install ./uh*.deb && ls /opt/uhelp
          echo "________________________________________"
          whereis uh

      - name: checklist1
        run: |
          uhelp ls && uh ls > uhout.txt

      - name: checklist2
        run: |
          echo y | uhelp -s sleep time
          echo y | uhelp -s i am sleep
          echo y | uhelp -s good night
          echo y | uhelp -s hello world
          echo y | uhelp -s sleep time again
          echo y | uhelp -s good night again
          echo y | uhelp -s hello
          echo y | uhelp -s sleep
          echo y | uhelp -s good night!
          echo y | uhelp -s morning!
          echo y | uhelp -s sleep note test
          echo y | uhelp -s hello world!
          echo n | uhelp -s i am check

      - name: checklist3
        run: |
          uh -v retro2
          uh uhelp


      - name: backup
        run: |
          echo y | uh -b backup
          ls ~/


      - name: tldr test
        run: |
          uh -t grep


